name: Go CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies 
        run: go mod tidy

      - name: run tests
        run: go test -v -cover

      - name: Building
        run: go build -o myapp

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp-binary
          path: myapp